name: project1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  carousel_slider: ^4.2.1
  flutter_svg: ^1.1.6
  smooth_page_indicator: ^1.0.0+2
  google_fonts: ^3.0.1
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.4
  firebase_storage: ^11.0.10
  firebase_database: ^10.0.9
  cloud_firestore: ^4.3.1
  fluttertoast: ^8.1.2
  provider: ^6.0.5
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  toggle_switch: ^2.0.1
  syncfusion_flutter_gauges: ^20.4.42
  camera: ^0.9.4+11
  uuid: ^3.0.7
  calendar_date_picker2: ^0.3.6

  cool_dropdown: ^1.4.2
  rflutter_alert: ^2.0.4
  http: ^0.13.5
  google_maps_flutter: ^2.2.3
  syncfusion_flutter_sliders: ^20.4.42
  map_launcher: ^2.4.0
  back_button_interceptor: ^6.0.2
  flutter_driver:
    sdk: flutter
  flutter_local_notifications: ^13.0.0
  firebase_messaging: ^14.2.1
  firebase_analytics: ^10.1.0
  flutter_email_sender: ^5.2.0
  motion_tab_bar_v2: ^0.2.6
  url_launcher: ^6.1.7
  syncfusion_flutter_charts: ^20.4.44
  countup: ^0.1.4
  data_table_2: ^2.3.10
  cloud_functions: ^4.0.7
  syncfusion_flutter_maps: ^20.4.44
  syncfusion_flutter_treemap: ^20.4.44-beta
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.3.0
  hellodoc_service_pkg:
    version: ^0.0.17
    hosted:
      name: hellodoc_service_pkg
      url: https://onepub.dev/api/avvdavuhno
  dio: ^4.0.6
  toggle_list: ^0.3.0
  flutter_neumorphic: ^3.2.0
  geocoding: ^2.1.0
  pdf: ^3.8.4
  syncfusion_flutter_pdf: ^20.4.54
  open_filex: ^4.3.2
  sliding_switch: ^1.1.0
  intl_phone_field: ^3.1.0
  country_calling_code_picker: ^2.0.1
  tap_to_expand: ^0.6.1
  flutter_easyloading: ^3.0.5
  material_dialogs: ^1.1.4

  






dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.11.0  

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launch_icon"
  ios: true
  image_path: "assets/images/crescent.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/hospitals.json
    - assets/images/activities.png
    - assets/images/logo.png
    - assets/images/bg.png
    - assets/images/healthcare.png
    - assets/images/medicine.png
    - assets/images/permission.png
    - assets/images/facebook.png
    - assets/images/linkedin.png
    - assets/images/instagram.png
    - assets/images/gallery.png
    - assets/images/calendar.png
    - assets/images/clock.png
    - assets/images/camera.png
    - assets/images/tick.png
    - assets/images/f.jpeg
    - assets/images/mstudent.png
    - assets/images/fstudent.png
    - assets/images/person.jpg
    - assets/images/doctor2.jpg
    - assets/images/crescent.jpg
    - assets/images/user.png
    - assets/images/call.png
    - assets/images/upload.gif
    - assets/images/g.jpg
    - assets/images/h.jpg
    - assets/images/l.jpeg
    - assets/images/j.png
    - assets/images/k.jpg
    - assets/images/calculator.png
    - assets/images/discounts.png
    - assets/images/doctor.png
    - assets/images/soon1.png
    - assets/images/soon2.png
    - assets/images/soon3.png
    - assets/images/doctorss.jpg
    - assets/images/flask.png
    - assets/images/map.png
    - assets/images/appointment.png
    - assets/images/muneer.jpg
    - assets/images/mubashir.jpeg
    - assets/images/faizan.jpeg
    - assets/images/world.jpg
    - assets/images/shahzad.jpg
    - assets/images/prescription.png
    - assets/images/plus.png
    - assets/images/minus.png
    - assets/images/o.jpg
    - assets/images/p.jpg
    - assets/images/menu.png
    - assets/svgs/about.svg
    - assets/svgs/contactus.svg
    - assets/svgs/doctor.svg
    - assets/svgs/pharm.svg
    - assets/svgs/lab.svg
    - assets/images/
    - assets/images/side.png
    - assets/images/cc.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
